version: '3.3'
services:
    app:
      build: ./
      image: app:1.0
      restart: always
      container_name: app
      ports:
        - 8008:8008
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
      network_mode: bridge